---
substitutions:
  hostname: "sonoff-s31"
  update_interval: 10s

esphome:
  name: $hostname

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  baud_rate: 0

api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_pass

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: $hostname Button
    on_press:
      - switch.toggle: relay
  - platform: status
    name: $hostname Status

sensor:
  - platform: wifi_signal
    name: $hostname WiFi Signal
    update_interval: ${update_interval}
  - platform: cse7766
    current:
      name: $hostname Current
      accuracy_decimals: 1
      filters:
        - throttle_average: ${update_interval}
    voltage:
      name: $hostname Voltage
      accuracy_decimals: 1
      filters:
        - throttle: ${update_interval}
    power:
      name: $hostname Power
      accuracy_decimals: 1
      id: my_power
      filters:
        - throttle: ${update_interval}
  - platform: integration
    name: $hostname Energy
    icon: mdi:battery
    sensor: my_power
    time_unit: h
    id: energy_used
    filters:
      - throttle: ${update_interval}

button:
  - platform: template
    name: $hostname Reset Energy
    icon: mdi:restart
    on_press:
      - sensor.integration.reset: energy_used

switch:
  - platform: gpio
    name: $hostname Relay
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_OFF

time:
  - platform: homeassistant
    id: homeassistant_time

status_led:
  pin:
    number: GPIO13
    inverted: True

text_sensor:
  - platform: version
    name: $hostname ESPHome Version
