---
# This config is essentially the same as the base Sonoff S31 config,
# but with some modifications to make it suitable for use on devices
# which should not be power cycled without care.
# The specific modifications are:
#   - the relay should not turn off when new firmware is flashed
#   - the relay defaults to being ON
#   - the button on the device is disabled
#   - a "Power Cycle" button is added which requires a "Confirm Restart"
#     switch to be set first
# Most of the enhancements are described by the following post:
# https://static.xtremeownage.com/blog/2023/esphome-on-critical-infrastructure/
substitutions:
  hostname: "sonoff-s31"
  friendly_name: "Sonoff S31"
  update_interval: 10s

esphome:
  name: $hostname
  friendly_name: $friendly_name

esp8266:
  board: esp01_1m
  early_pin_init: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  baud_rate: 0

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_pass

uart:
  rx_pin: RX
  baud_rate: 4800

globals:
  - id: confirm_restart
    type: bool
    restore_value: no
    initial_value: 'false'

binary_sensor:
  - platform: status
    name: Status

sensor:
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: ${update_interval}
  - platform: cse7766
    current:
      name: Current
      accuracy_decimals: 1
      filters:
        - throttle_average: ${update_interval}
    voltage:
      name: Voltage
      accuracy_decimals: 1
      filters:
        - throttle: ${update_interval}
    power:
      name: Power
      accuracy_decimals: 1
      id: my_power
      filters:
        - throttle: ${update_interval}
  - platform: integration
    name: Energy
    icon: mdi:battery
    sensor: my_power
    time_unit: h
    id: energy_used
    filters:
      - throttle: ${update_interval}
  - platform: uptime
    name: Uptime

button:
  - platform: restart
    name: Restart
  - platform: template
    name: Reset Energy
    icon: mdi:restart
    on_press:
      - sensor.integration.reset: energy_used
  - platform: template
    name: Power Cycle
    icon: mdi:restart-alert
    on_press:
      - if:
          condition:
            lambda: 'return id(confirm_restart);'
          then:
            - switch.turn_off: confirm_restart_sw
            - switch.turn_off: relay
            - delay: 5s
            - switch.turn_on: relay

switch:
  - platform: gpio
    pin: GPIO12
    id: relay
    internal: true
    restore_mode: ALWAYS_ON
  - platform: template
    name: Confirm Restart
    id: confirm_restart_sw
    icon: mdi:alert
    lambda: |-
      return id(confirm_restart);
    turn_on_action:
      - lambda: |-
          id(confirm_restart) = true;
    turn_off_action:
      - lambda: |-
          id(confirm_restart) = false;

time:
  - platform: homeassistant
    id: homeassistant_time

status_led:
  pin:
    number: GPIO13
    inverted: true

text_sensor:
  - platform: version
    name: ESPHome Version
